changelog:
  exclude:
    labels:
      - dependencies
      - ci
    authors:
      - dependabot
  categories:
    - title: Breaking Changes
      labels:
        - breaking
        - breaking-change
    - title: Features
      labels:
        - feat
        - feature
        - enhancement
    - title: Bug Fixes
      labels:
        - fix
        - bug
    - title: Documentation
      labels:
        - docs
    - title: Other Changes
      labels:
        - "*"
