root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/embookshelf ./cmd/embookshelf"
  bin = "./tmp/embookshelf"
  include_ext = ["go", "sql"]
  exclude_dir = ["tmp", "frontend", "node_modules", ".git", "internal/repo/generated", "internal/staticfs/dist"]
  kill_delay = "1s"
  stop_on_error = true
  delay = 500

[log]
  time = true

[color]
  main = "magenta"
  watcher = "cyan"
  build = "yellow"
  runner = "green"
