/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as ReadIdRouteImport } from './routes/read.$id'
import { Route as LoginPendingRouteImport } from './routes/login.pending'
import { Route as AppStatsRouteImport } from './routes/_app.stats'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppNotebookRouteImport } from './routes/_app.notebook'
import { Route as AppLibraryRouteImport } from './routes/_app.library'
import { Route as AppBookdropRouteImport } from './routes/_app.bookdrop'
import { Route as AppBookIdRouteImport } from './routes/_app.book.$id'
import { Route as AppBookIdEditRouteImport } from './routes/_app.book.$id_.edit'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const ReadIdRoute = ReadIdRouteImport.update({
  id: '/read/$id',
  path: '/read/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginPendingRoute = LoginPendingRouteImport.update({
  id: '/pending',
  path: '/pending',
  getParentRoute: () => LoginRoute,
} as any)
const AppStatsRoute = AppStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppNotebookRoute = AppNotebookRouteImport.update({
  id: '/notebook',
  path: '/notebook',
  getParentRoute: () => AppRoute,
} as any)
const AppLibraryRoute = AppLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AppRoute,
} as any)
const AppBookdropRoute = AppBookdropRouteImport.update({
  id: '/bookdrop',
  path: '/bookdrop',
  getParentRoute: () => AppRoute,
} as any)
const AppBookIdRoute = AppBookIdRouteImport.update({
  id: '/book/$id',
  path: '/book/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppBookIdEditRoute = AppBookIdEditRouteImport.update({
  id: '/book/$id_/edit',
  path: '/book/$id/edit',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRouteWithChildren
  '/bookdrop': typeof AppBookdropRoute
  '/library': typeof AppLibraryRoute
  '/notebook': typeof AppNotebookRoute
  '/settings': typeof AppSettingsRoute
  '/stats': typeof AppStatsRoute
  '/login/pending': typeof LoginPendingRoute
  '/read/$id': typeof ReadIdRoute
  '/book/$id': typeof AppBookIdRoute
  '/book/$id/edit': typeof AppBookIdEditRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRouteWithChildren
  '/bookdrop': typeof AppBookdropRoute
  '/library': typeof AppLibraryRoute
  '/notebook': typeof AppNotebookRoute
  '/settings': typeof AppSettingsRoute
  '/stats': typeof AppStatsRoute
  '/login/pending': typeof LoginPendingRoute
  '/read/$id': typeof ReadIdRoute
  '/': typeof AppIndexRoute
  '/book/$id': typeof AppBookIdRoute
  '/book/$id/edit': typeof AppBookIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRouteWithChildren
  '/_app/bookdrop': typeof AppBookdropRoute
  '/_app/library': typeof AppLibraryRoute
  '/_app/notebook': typeof AppNotebookRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/stats': typeof AppStatsRoute
  '/login/pending': typeof LoginPendingRoute
  '/read/$id': typeof ReadIdRoute
  '/_app/': typeof AppIndexRoute
  '/_app/book/$id': typeof AppBookIdRoute
  '/_app/book/$id_/edit': typeof AppBookIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/bookdrop'
    | '/library'
    | '/notebook'
    | '/settings'
    | '/stats'
    | '/login/pending'
    | '/read/$id'
    | '/book/$id'
    | '/book/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/bookdrop'
    | '/library'
    | '/notebook'
    | '/settings'
    | '/stats'
    | '/login/pending'
    | '/read/$id'
    | '/'
    | '/book/$id'
    | '/book/$id/edit'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/bookdrop'
    | '/_app/library'
    | '/_app/notebook'
    | '/_app/settings'
    | '/_app/stats'
    | '/login/pending'
    | '/read/$id'
    | '/_app/'
    | '/_app/book/$id'
    | '/_app/book/$id_/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRouteWithChildren
  ReadIdRoute: typeof ReadIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/read/$id': {
      id: '/read/$id'
      path: '/read/$id'
      fullPath: '/read/$id'
      preLoaderRoute: typeof ReadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/pending': {
      id: '/login/pending'
      path: '/pending'
      fullPath: '/login/pending'
      preLoaderRoute: typeof LoginPendingRouteImport
      parentRoute: typeof LoginRoute
    }
    '/_app/stats': {
      id: '/_app/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof AppStatsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notebook': {
      id: '/_app/notebook'
      path: '/notebook'
      fullPath: '/notebook'
      preLoaderRoute: typeof AppNotebookRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/library': {
      id: '/_app/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof AppLibraryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/bookdrop': {
      id: '/_app/bookdrop'
      path: '/bookdrop'
      fullPath: '/bookdrop'
      preLoaderRoute: typeof AppBookdropRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/book/$id': {
      id: '/_app/book/$id'
      path: '/book/$id'
      fullPath: '/book/$id'
      preLoaderRoute: typeof AppBookIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/book/$id_/edit': {
      id: '/_app/book/$id_/edit'
      path: '/book/$id/edit'
      fullPath: '/book/$id/edit'
      preLoaderRoute: typeof AppBookIdEditRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppBookdropRoute: typeof AppBookdropRoute
  AppLibraryRoute: typeof AppLibraryRoute
  AppNotebookRoute: typeof AppNotebookRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppStatsRoute: typeof AppStatsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppBookIdRoute: typeof AppBookIdRoute
  AppBookIdEditRoute: typeof AppBookIdEditRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBookdropRoute: AppBookdropRoute,
  AppLibraryRoute: AppLibraryRoute,
  AppNotebookRoute: AppNotebookRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppStatsRoute: AppStatsRoute,
  AppIndexRoute: AppIndexRoute,
  AppBookIdRoute: AppBookIdRoute,
  AppBookIdEditRoute: AppBookIdEditRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface LoginRouteChildren {
  LoginPendingRoute: typeof LoginPendingRoute
}

const LoginRouteChildren: LoginRouteChildren = {
  LoginPendingRoute: LoginPendingRoute,
}

const LoginRouteWithChildren = LoginRoute._addFileChildren(LoginRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRouteWithChildren,
  ReadIdRoute: ReadIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
