/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AcceptInviteRouteImport } from './routes/accept-invite'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ResetRouteImport } from './routes/reset'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppAccountRouteImport } from './routes/_app.account'
import { Route as AppBookdropRouteImport } from './routes/_app.bookdrop'
import { Route as AppLibraryRouteImport } from './routes/_app.library'
import { Route as AppNotebookRouteImport } from './routes/_app.notebook'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppStatsRouteImport } from './routes/_app.stats'
import { Route as LoginPendingRouteImport } from './routes/login_.pending'
import { Route as ReadIdRouteImport } from './routes/read.$id'
import { Route as AppBookIdRouteImport } from './routes/_app.book.$id'
import { Route as AppBookIdEditRouteImport } from './routes/_app.book.$id_.edit'
import { Route as AppBookIdFindRouteImport } from './routes/_app.book.$id_.find'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInviteRoute = AcceptInviteRouteImport.update({
  id: '/accept-invite',
  path: '/accept-invite',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetRoute = ResetRouteImport.update({
  id: '/reset',
  path: '/reset',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountRoute = AppAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AppRoute,
} as any)
const AppBookdropRoute = AppBookdropRouteImport.update({
  id: '/bookdrop',
  path: '/bookdrop',
  getParentRoute: () => AppRoute,
} as any)
const AppLibraryRoute = AppLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AppRoute,
} as any)
const AppNotebookRoute = AppNotebookRouteImport.update({
  id: '/notebook',
  path: '/notebook',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppStatsRoute = AppStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => AppRoute,
} as any)
const LoginPendingRoute = LoginPendingRouteImport.update({
  id: '/login_/pending',
  path: '/login/pending',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadIdRoute = ReadIdRouteImport.update({
  id: '/read/$id',
  path: '/read/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AppBookIdRoute = AppBookIdRouteImport.update({
  id: '/book/$id',
  path: '/book/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppBookIdEditRoute = AppBookIdEditRouteImport.update({
  id: '/book/$id_/edit',
  path: '/book/$id/edit',
  getParentRoute: () => AppRoute,
} as any)
const AppBookIdFindRoute = AppBookIdFindRouteImport.update({
  id: '/book/$id_/find',
  path: '/book/$id/find',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset': typeof ResetRoute
  '/account': typeof AppAccountRoute
  '/bookdrop': typeof AppBookdropRoute
  '/library': typeof AppLibraryRoute
  '/notebook': typeof AppNotebookRoute
  '/settings': typeof AppSettingsRoute
  '/stats': typeof AppStatsRoute
  '/login/pending': typeof LoginPendingRoute
  '/read/$id': typeof ReadIdRoute
  '/book/$id': typeof AppBookIdRoute
  '/book/$id/edit': typeof AppBookIdEditRoute
  '/book/$id/find': typeof AppBookIdFindRoute
}
export interface FileRoutesByTo {
  '/accept-invite': typeof AcceptInviteRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset': typeof ResetRoute
  '/account': typeof AppAccountRoute
  '/bookdrop': typeof AppBookdropRoute
  '/library': typeof AppLibraryRoute
  '/notebook': typeof AppNotebookRoute
  '/settings': typeof AppSettingsRoute
  '/stats': typeof AppStatsRoute
  '/login/pending': typeof LoginPendingRoute
  '/read/$id': typeof ReadIdRoute
  '/': typeof AppIndexRoute
  '/book/$id': typeof AppBookIdRoute
  '/book/$id/edit': typeof AppBookIdEditRoute
  '/book/$id/find': typeof AppBookIdFindRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/accept-invite': typeof AcceptInviteRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset': typeof ResetRoute
  '/_app/account': typeof AppAccountRoute
  '/_app/bookdrop': typeof AppBookdropRoute
  '/_app/library': typeof AppLibraryRoute
  '/_app/notebook': typeof AppNotebookRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/stats': typeof AppStatsRoute
  '/login_/pending': typeof LoginPendingRoute
  '/read/$id': typeof ReadIdRoute
  '/_app/': typeof AppIndexRoute
  '/_app/book/$id': typeof AppBookIdRoute
  '/_app/book/$id_/edit': typeof AppBookIdEditRoute
  '/_app/book/$id_/find': typeof AppBookIdFindRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accept-invite'
    | '/forgot-password'
    | '/login'
    | '/reset'
    | '/account'
    | '/bookdrop'
    | '/library'
    | '/notebook'
    | '/settings'
    | '/stats'
    | '/login/pending'
    | '/read/$id'
    | '/book/$id'
    | '/book/$id/edit'
    | '/book/$id/find'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/accept-invite'
    | '/forgot-password'
    | '/login'
    | '/reset'
    | '/account'
    | '/bookdrop'
    | '/library'
    | '/notebook'
    | '/settings'
    | '/stats'
    | '/login/pending'
    | '/read/$id'
    | '/'
    | '/book/$id'
    | '/book/$id/edit'
    | '/book/$id/find'
  id:
    | '__root__'
    | '/_app'
    | '/accept-invite'
    | '/forgot-password'
    | '/login'
    | '/reset'
    | '/_app/account'
    | '/_app/bookdrop'
    | '/_app/library'
    | '/_app/notebook'
    | '/_app/settings'
    | '/_app/stats'
    | '/login_/pending'
    | '/read/$id'
    | '/_app/'
    | '/_app/book/$id'
    | '/_app/book/$id_/edit'
    | '/_app/book/$id_/find'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AcceptInviteRoute: typeof AcceptInviteRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetRoute: typeof ResetRoute
  LoginPendingRoute: typeof LoginPendingRoute
  ReadIdRoute: typeof ReadIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invite': {
      id: '/accept-invite'
      path: '/accept-invite'
      fullPath: '/accept-invite'
      preLoaderRoute: typeof AcceptInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset': {
      id: '/reset'
      path: '/reset'
      fullPath: '/reset'
      preLoaderRoute: typeof ResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/account': {
      id: '/_app/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AppAccountRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/bookdrop': {
      id: '/_app/bookdrop'
      path: '/bookdrop'
      fullPath: '/bookdrop'
      preLoaderRoute: typeof AppBookdropRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/library': {
      id: '/_app/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof AppLibraryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notebook': {
      id: '/_app/notebook'
      path: '/notebook'
      fullPath: '/notebook'
      preLoaderRoute: typeof AppNotebookRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/stats': {
      id: '/_app/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof AppStatsRouteImport
      parentRoute: typeof AppRoute
    }
    '/login_/pending': {
      id: '/login_/pending'
      path: '/login/pending'
      fullPath: '/login/pending'
      preLoaderRoute: typeof LoginPendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/read/$id': {
      id: '/read/$id'
      path: '/read/$id'
      fullPath: '/read/$id'
      preLoaderRoute: typeof ReadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/book/$id': {
      id: '/_app/book/$id'
      path: '/book/$id'
      fullPath: '/book/$id'
      preLoaderRoute: typeof AppBookIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/book/$id_/edit': {
      id: '/_app/book/$id_/edit'
      path: '/book/$id/edit'
      fullPath: '/book/$id/edit'
      preLoaderRoute: typeof AppBookIdEditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/book/$id_/find': {
      id: '/_app/book/$id_/find'
      path: '/book/$id/find'
      fullPath: '/book/$id/find'
      preLoaderRoute: typeof AppBookIdFindRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAccountRoute: typeof AppAccountRoute
  AppBookdropRoute: typeof AppBookdropRoute
  AppLibraryRoute: typeof AppLibraryRoute
  AppNotebookRoute: typeof AppNotebookRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppStatsRoute: typeof AppStatsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppBookIdRoute: typeof AppBookIdRoute
  AppBookIdEditRoute: typeof AppBookIdEditRoute
  AppBookIdFindRoute: typeof AppBookIdFindRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAccountRoute: AppAccountRoute,
  AppBookdropRoute: AppBookdropRoute,
  AppLibraryRoute: AppLibraryRoute,
  AppNotebookRoute: AppNotebookRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppStatsRoute: AppStatsRoute,
  AppIndexRoute: AppIndexRoute,
  AppBookIdRoute: AppBookIdRoute,
  AppBookIdEditRoute: AppBookIdEditRoute,
  AppBookIdFindRoute: AppBookIdFindRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AcceptInviteRoute: AcceptInviteRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetRoute: ResetRoute,
  LoginPendingRoute: LoginPendingRoute,
  ReadIdRoute: ReadIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
