// SPDX-License-Identifier: AGPL-3.0-or-later

package task

// The BookDrop pipeline driven end to end for .cbr and .cb7 (#310):
// Intake (the row a watcher or upload would create), BookDropIngest (the
// real fileproc.Dispatch + ExtractBook pass — the thing that used to
// answer "no processor for CBZ yet" for both extensions before this issue
// wired one), and Approve (placement + the books row). A real Postgres
// schema and a real local storage backend throughout, via
// bookDropPipeline (bookdrop_pipeline_test.go) — the same harness the
// MOBI and FB2 pipeline tests use.
//
// The archives come from internal/fileproc/testdata rather than from a
// copy here: they are the fixtures that package's unit tests are written
// against, and two copies of a binary fixture is two things to keep in
// step. The RAR one is generated by the writer in fileproc's cbr_test.go
// (which checks the committed copy still matches it); the 7z one is a
// real 7-Zip archive, because nothing in Go writes 7z.

import (
	"context"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/blackforge/embookshelf/internal/jobs"
	"github.com/blackforge/embookshelf/internal/model"
)

const (
	comicFixtureCBR          = "../fileproc/testdata/comic.cbr"
	comicFixtureCB7          = "../fileproc/testdata/comic.cb7"
	comicFixtureEncryptedCB7 = "../fileproc/testdata/comic-encrypted.cb7"
)

func TestBookDropIngest_Comic_IntakeIngestApprove(t *testing.T) {
	cases := []struct {
		name    string
		file    string
		fixture string
	}{
		{name: "cbr", file: "saga-01.cbr", fixture: comicFixtureCBR},
		{name: "cb7", file: "saga-01.cb7", fixture: comicFixtureCB7},
	}
	for _, c := range cases {
		t.Run(c.name, func(t *testing.T) {
			ctx := context.Background()
			p := newBookDropPipeline(t)
			path := p.stage(t, c.file, readFixtureFile(t, c.fixture))

			// --- intake: the watcher's path -------------------------------
			item, created, err := p.svc.Intake(ctx, path)
			if err != nil {
				t.Fatalf("Intake: %v", err)
			}
			if !created {
				t.Fatal("Intake: created = false, want true")
			}
			// The table folds every comic extension onto CBZ.
			if item.Format != "CBZ" {
				t.Fatalf("Intake: item.Format = %q, want CBZ", item.Format)
			}

			// --- ingest: the real fileproc.Dispatch + ExtractBook pass ----
			// Before #310 this failed the item with fileproc.NoProcessorError;
			// this is the call that would have produced that refusal.
			if err := BookDropIngest(ctx, jobs.BookDropIngestArgs{ItemID: item.ID}, BookDropDeps{
				Svc:      p.svc,
				Resolver: p.resolver,
			}); err != nil {
				t.Fatalf("BookDropIngest: %v", err)
			}

			ingested, err := p.svc.Get(ctx, item.ID)
			if err != nil {
				t.Fatalf("Get after ingest: %v", err)
			}
			if ingested.State != model.BookDropReady {
				t.Fatalf("state = %q (error %q), want ready", ingested.State, ingested.ErrorMsg)
			}
			if ingested.Title != "Saga #1" {
				t.Errorf("Title = %q, want %q — ComicInfo.xml was not read", ingested.Title, "Saga #1")
			}
			if ingested.Author != "Brian K. Vaughan" {
				t.Errorf("Author = %q, want %q", ingested.Author, "Brian K. Vaughan")
			}
			if !ingested.HasCover {
				t.Error("expected HasCover after ingest")
			}
			if ingested.ContentHash == nil {
				t.Error("expected a content hash to have been recorded")
			}

			// --- approve: placement + the books row -----------------------
			book, err := p.svc.Approve(ctx, item.ID, p.lib.ID)
			if err != nil {
				t.Fatalf("Approve: %v", err)
			}
			if book.Format != "CBZ" {
				t.Errorf("book.Format = %q, want CBZ", book.Format)
			}
			if book.Title != "Saga #1" {
				t.Errorf("book.Title = %q", book.Title)
			}
			if !book.HasCover {
				t.Error("expected the approved book to carry a cover")
			}

			wantLocation := filepath.Join("Brian K. Vaughan", "Saga #1", c.file)
			if book.Path != wantLocation {
				t.Errorf("book.Path = %q, want %q", book.Path, wantLocation)
			}
			if _, err := os.Stat(filepath.Join(p.libRoot, wantLocation)); err != nil {
				t.Errorf("approved bytes are not inside the library: %v", err)
			}

			final, err := p.svc.Get(ctx, item.ID)
			if err != nil {
				t.Fatalf("Get after approve: %v", err)
			}
			if final.State != model.BookDropImported {
				t.Errorf("state = %q, want imported", final.State)
			}
		})
	}
}

// An archive this cannot read fails the item with a message rather than
// panicking the ingest worker or landing a half-empty book on the shelf —
// and the two reasons it might not read are told apart, because a
// password-protected file is a good file we will not open and a truncated
// one is a bad file to replace.
func TestBookDropIngest_Comic_UnreadableArchivesFailTheItem(t *testing.T) {
	truncated := readFixtureFile(t, comicFixtureCBR)
	truncated = truncated[:len(truncated)/2]

	cases := []struct {
		name     string
		file     string
		raw      []byte
		wantWord string
	}{
		{
			name:     "password-protected cb7",
			file:     "locked.cb7",
			raw:      readFixtureFile(t, comicFixtureEncryptedCB7),
			wantWord: "password",
		},
		{
			name: "truncated cbr",
			file: "broken.cbr",
			raw:  truncated,
			// No word to insist on beyond the container's name: what
			// rardecode says about the bytes is its own.
			wantWord: "cbr",
		},
	}
	for _, c := range cases {
		t.Run(c.name, func(t *testing.T) {
			ctx := context.Background()
			p := newBookDropPipeline(t)
			path := p.stage(t, c.file, c.raw)

			item, _, err := p.svc.Intake(ctx, path)
			if err != nil {
				t.Fatalf("Intake: %v", err)
			}

			// The worker call must return — with or without an error —
			// rather than panic; the item's own state is where the failure
			// is recorded.
			_ = BookDropIngest(ctx, jobs.BookDropIngestArgs{ItemID: item.ID}, BookDropDeps{
				Svc:      p.svc,
				Resolver: p.resolver,
			})

			failed, err := p.svc.Get(ctx, item.ID)
			if err != nil {
				t.Fatalf("Get after ingest: %v", err)
			}
			if failed.State != model.BookDropFailed {
				t.Fatalf("state = %q, want error for an unreadable archive", failed.State)
			}
			if !strings.Contains(strings.ToLower(failed.ErrorMsg), c.wantWord) {
				t.Errorf("ErrorMsg = %q, want it to mention %q", failed.ErrorMsg, c.wantWord)
			}
		})
	}
}
